name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  branch-name:
    description: 'The name of the branch'
    required: true
    default: 'test-branch'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'